### ISSUE TITLE
fatal: repository 'https://github.com/bryk-io/x/' not found

### ISSUE THREAD

**Issue by zhanb** [bryk-io/did-method#1]
go: github.com/bryk-io/x@v0.0.0-20191201183948-176f35bef721: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in F:\project\GoRoot\bin\pkg\mod\cache\vcs\e92a3263c457e9cb81144ecd1ef780e2861da7582484dbd454a5fbb51c932646: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/bryk-io/x/' not found

**Comment by bcessa** [comment]
Hi, currently the package __'x'__ is a private module published under https://go.bryk.io/x

We expect to soon publish the source for those packages as well. In the meantime you can download pre-compiled binaries for all the major platforms directly on the "Releases" section of the repository.
https://github.com/bryk-io/did-method/releases
